version: '3'
services:
  prestashop:
    image: takbytobylo/be_18430:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${DB_PASSWD:-student}
      DB_NAME: ${DB_NAME:-BE_184309}
      DB_SERVER: ${DB_SERVER:-db}
      DB_PREFIX: ${DB_PREFIX:-ps_}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:18430}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-pl}
      PS_LANGUAGE: ${PS_LANGUAGE:-pl}
      PS_DEV_MODE: ${PS_DEV_MODE:-0}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-prestashop_demo}
      PS_ERASE_DB: ${PS_ERASE_DB:-0}
    #command: ["/tmp/launch.sh"]
    ports:
      - "18430:443"
    networks:
      - admin-mysql_default

networks:
  admin-mysql_default:
    external: true