version: '3.9'
services:
  mysql:
    image: mysql:8
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 3306:3306
    networks:
      - prestashop
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql_tools/backup.sh:/sql_tools/backup.sh
      - ./sql_tools/restore.sh:/sql_tools/restore.sh
      - ./mysql_backup/:/var/lib/mysql/db_backup

  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    environment:
      DB_SERVER: mysql
    ports:
      - 8080:80
    networks:
      - prestashop
    volumes:
      - ./prestashop_data:/var/www/html
 
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - prestashop_data:/var/www/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs:/etc/ssl/certs
    depends_on:
      - prestashop
    networks:
      - prestashop
 
networks:
  prestashop:
 
volumes:
  mysql_data:
  prestashop_data:
