<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYc6lqrl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYc6lqrl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYc6lqrl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYc6lqrl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYc6lqrl\appProdProjectContainer([
    'container.build_hash' => 'Yc6lqrl',
    'container.build_id' => 'b8c54910',
    'container.build_time' => 1701715658,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYc6lqrl');
