<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDyuppkn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDyuppkn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDyuppkn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDyuppkn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDyuppkn\appProdProjectContainer([
    'container.build_hash' => 'Dyuppkn',
    'container.build_id' => 'a3fda012',
    'container.build_time' => 1702388165,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDyuppkn');
