<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1dq1tgx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1dq1tgx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container1dq1tgx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container1dq1tgx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container1dq1tgx\appProdProjectContainer([
    'container.build_hash' => '1dq1tgx',
    'container.build_id' => '64b57ffc',
    'container.build_time' => 1702511860,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1dq1tgx');
